### PR TITLE
Theme Selection, Refuse Floor Boss Gift

### PR DESCRIPTION
**Pull request by PasathornP**
Theme Selection
-Order from EventTheme.png (Can replace yourself to any theme you prefer or new event theme it gonna first priority select, to avoid select event theme just replace them with other theme and rename it to EventTheme.png) also if no prefer theme found it gonna click reset once
//To Do Replace Capture Theme Pic (Some of theme still from wiki which is not detect by program idk)
//To Do I try to use transparent LimbosCompany Icon on ThemePack as random select if other theme not found (mostly with 1 reset it gonna found at least one for me) so this needed to be test

Mirror4Entry
-Select Poise and first and second ego gift on the start (can replace PoiseEgoGift.png to any) >> or maybe replace name to something else like startEgoGift.png

Mirror4
-Refuse EgoGift if it from floor's boss to avoid negative debuff

### CODE REVIEW

**Comment by HSLix** [comment]
thanks :)

> Theme Selection 
great :)

> Mirror4Entry
> -Select Poise and
anyway, lalc would alway chooses poise within a few weeks, which is also my team's favourite

> Mirror4 -Refuse EgoGift if it from floor's boss to avoid negative debuff
this may not be as useful as you think, due to the pic below
image

all in all,, great :)

**Comment by HSLix** [comment]
in my opinion, these issue could close after this update
#86 #87 #90 #92 #95 #100 #101 #102 #103

**Comment by HSLix** [comment]
thankfully，it merge successfully. I just think I failed.And thanks again :)

**Comment by PasathornP** [comment]
> thanks :)
> 
> > Theme Selection
> 
> great :)
> 
> > Mirror4Entry
> > -Select Poise and
> 
> anyway, lalc would alway chooses poise within a few weeks, which is also my team's favourite
> 
> > Mirror4 -Refuse EgoGift if it from floor's boss to avoid negative debuff
> 
> this may not be as useful as you think, due to the pic below image
> 
> all in all,, great :)

wait is this new update? I still think no gift = no floor buff since forever xd I always skip any popup and tldr

**Pull request merged**
